spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/echo}
    driverClassName: ${DB_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:theskysid}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
jwt:
  secret: FGW390@#7&Ounjkebu!#%%GHOPQasx&Q
  expiration: 3600000